sonar.projectKey=SOAT-FIAP-GROUP_hackaton_video_processor
sonar.organization=soat-fiap-group

sonar.sources=apps/worker
sonar.tests=apps/worker

sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out