apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processor-worker-app
  template:
    metadata:
      labels:
        app: video-processor-worker-app
    spec:
      containers:
      - name: video-processor-worker-container
        image: ${DOCKER_IMAGE_WORKER}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: us-east-1      
        - name: AWS_S3_BUCKET
          valueFrom:
              configMapKeyRef:
                name: video-processor-worker-config
                key: aws.bucket.name
        - name: AWS_SQS_QUEUE_NAME_VIDEO_PROCESSING
          valueFrom:
              configMapKeyRef:
                name: video-processor-worker-config
                key: aws.queue.name.videoprocessing
        - name: AWS_SQS_QUEUE_NAME_NOTIFICATION
          valueFrom:
              configMapKeyRef:
                name: video-processor-worker-config
                key: aws.queue.name.notification
        - name: COGNITO_CLIENT_ID
          valueFrom:
              configMapKeyRef:
                name: video-processor-worker-config
                key: aws.congnito.client.id
        - name: COGNITO_CLIENT_SECRET
          valueFrom:
              secretKeyRef:
                name: video-processor-secret
                key: aws.congnito.client.secret
        - name: COGNITO_USER_POOL_ID
          valueFrom:
              configMapKeyRef:
                name: video-processor-worker-config
                key: aws.congnito.user-pool.id
        - name: GIN_MODE
          value: release
        - name: API_PORT
          value: 8080
        - name: TEMP_PATH
          value: /unknown
        - name: DB_HOST
          valueFrom:
              configMapKeyRef:
                name: video-processor-worker-config
                key: db.host
        - name: DB_NAME
          value: video_processor
        - name: DB_REPLICA_NAME
          value: video_processor_replica
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: video-processor-secret
                key: db.password
        - name: DB_PORT
          value: 5432
        - name: DB_SSL_MODE
          value: require
        - name: DB_USER
          value: postgres 
        resources:
          requests:
            cpu: "100m"
            memory: 200Mi
          limits:
            cpu: "300m"
            memory: 400Mi
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: 8080
        #   initialDelaySeconds: 120
        #   periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health/readiness
        #     port: 8080
        #   initialDelaySeconds: 120
        #   periodSeconds: 5