name: Build Docker Image

on:
  workflow_run:
    workflows: ["SonarCloud Scan"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker-image: ${{ steps.build.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image API
        id: build1
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/video_processor_api:latest
          docker build -t $IMAGE ./.docker/api.Dockerfile
          docker push $IMAGE
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image WORKER
        id: build2
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/video_processor_worker:latest
          docker build -t $IMAGE ./.docker/api.Dockerfile
          docker push $IMAGE
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
