name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      force-deploy:
        description: 'Força a execução do deploy'
        required: false
        default: 'true'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.inputs.force-deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker images variables
        run: |
          DOCKER_IMAGE_API="${{ secrets.DOCKER_USERNAME }}/video_processor_api:latest"
          DOCKER_IMAGE_WORKER="${{ secrets.DOCKER_USERNAME }}/video_processor_worker:latest"
          echo "DOCKER_IMAGE_WORKER=$DOCKER_IMAGE_WORKER" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_API=$DOCKER_IMAGE_API" >> $GITHUB_ENV

      - name: Render Deployments
        run: |
          envsubst < k8s/api/deployment.yaml > k8s/api/deployment_rendered.yaml
          envsubst < k8s/worker/deployment.yaml > k8s/worker/deployment_rendered.yaml

      - name: Configure kubectl
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN_EKS }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get SSM parameters
        id: ssm
        run: |
          AWS_S3_BUCKET=$(aws ssm get-parameter --name "S3_BUCKET" --region us-east-1)
          AWS_SQS_QUEUE_NAME_VIDEO_PROCESSING=$(aws ssm get-parameter --name "SQS_QUEUE_NAME_VIDEO_PROCESSING" --with-decryption --query "Parameter.Value" --output text)
          AWS_SQS_QUEUE_NAME_NOTIFICATION=$(aws ssm get-parameter --name "SQS_QUEUE_NAME_NOTIFICATION" --with-decryption --query "Parameter.Value" --output text)
          COGNITO_CLIENT_ID=$(aws ssm get-parameter --name "COGNITO_CLIENT_ID" --with-decryption --query "Parameter.Value" --output text)
          COGNITO_CLIENT_SECRET=$(aws ssm get-parameter --name "COGNITO_CLIENT_SECRET" --with-decryption --query "Parameter.Value" --output text)
          COGNITO_USER_POOL_ID=$(aws ssm get-parameter --name "COGNITO_USER_POOL_ID" --with-decryption --query "Parameter.Value" --output text)
          DB_HOST=$(aws ssm get-parameter --name "DB_HOST" --with-decryption --query "Parameter.Value" --output text)
          DB_USER=$(aws ssm get-parameter --name "DB_USER" --with-decryption --query "Parameter.Value" --output text)
          DB_PASSWORD=$(aws ssm get-parameter --name "DB_PASSWORD" --with-decryption --query "Parameter.Value" --output text)

          echo "AWS_S3_BUCKET=$AWS_S3_BUCKET" >> $GITHUB_OUTPUT
          echo "AWS_SQS_QUEUE_NAME_VIDEO_PROCESSING=$AWS_SQS_QUEUE_NAME_VIDEO_PROCESSING" >> $GITHUB_OUTPUT
          echo "AWS_SQS_QUEUE_NAME_NOTIFICATION=$AWS_SQS_QUEUE_NAME_NOTIFICATION" >> $GITHUB_OUTPUT
          echo "COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID" >> $GITHUB_OUTPUT
          echo "COGNITO_CLIENT_SECRET=$COGNITO_CLIENT_SECRET" >> $GITHUB_OUTPUT
          echo "COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID" >> $GITHUB_OUTPUT
          echo "DB_HOST=$DB_HOST" >> $GITHUB_OUTPUT
          echo "DB_USER=$DB_USER" >> $GITHUB_OUTPUT
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_OUTPUT

      - name: Render ConfigMaps
        run: |
          export AWS_S3_BUCKET="${{ steps.ssm.outputs.AWS_S3_BUCKET }}"
          export AWS_SQS_QUEUE_NAME_VIDEO_PROCESSING="${{ steps.ssm.outputs.AWS_SQS_QUEUE_NAME_VIDEO_PROCESSING }}"
          export AWS_SQS_QUEUE_NAME_NOTIFICATION="${{ steps.ssm.outputs.AWS_SQS_QUEUE_NAME_NOTIFICATION }}"
          export COGNITO_CLIENT_ID="${{ steps.ssm.outputs.COGNITO_CLIENT_ID }}"
          export COGNITO_USER_POOL_ID="${{ steps.ssm.outputs.COGNITO_USER_POOL_ID }}"
          export DB_HOST="${{ steps.ssm.outputs.DB_HOST }}"
          export DB_USER="${{ steps.ssm.outputs.DB_USER }}"

          envsubst < k8s/api/configmap.yaml > k8s/api/configmap_rendered.yaml
          envsubst < k8s/worker/configmap.yaml > k8s/worker/configmap_rendered.yaml

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name hakaton-app-dev --region ${{ vars.AWS_REGION }}

      - name: Apply Kubernetes Secrets 
        if: ${{ inputs.destroy != 'true' }}
        run: |
          kubectl create secret generic video-processor-secret \
            --from-literal=aws.cognito.client.secret=${{ steps.ssm.outputs.COGNITO_CLIENT_SECRET }} \
            --from-literal=db.password=${{ steps.ssm.outputs.DB_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/api
          kubectl apply -f k8s/worker
          kubectl rollout status deployment/video-processor-api-app
          kubectl rollout status deployment/video-processor-worker-app
